"""
Project Initializer - Three-mode initialization (new/clone/local).

Mode A (new): Create fresh project directory with scaffold.
Mode B (clone): Clone from GitHub, scan, create dev branch.
Mode C (local): Scan existing directory, identify tech stack.
"""

import logging
import os
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from .models import ProjectRecord, ProjectStatus, ProjectInitMode

logger = logging.getLogger(__name__)

_DEFAULT_SCAFFOLD_DIRS = ["src", "tests", "docs"]
_DEFAULT_SCAFFOLD_FILES = {
    "README.md": "# {name}\n\nAuto-generated by MAP project-manage.\n",
    ".gitignore": "__pycache__/\n*.pyc\n.env\n.venv/\nnode_modules/\n",
}


class ProjectInitializer:
    def __init__(self, state_dir: str = None, registry=None, packs=None):
        self._state_dir = state_dir
        self._registry = registry
        self._packs = packs

    def initialize(self, description: str, context: Dict[str, Any]) -> Dict[str, Any]:
        mode = context.get("mode", "new")
        if mode == ProjectInitMode.NEW.value:
            return self._init_new(description, context)
        elif mode == ProjectInitMode.CLONE.value:
            return self._init_clone(description, context)
        elif mode == ProjectInitMode.LOCAL.value:
            return self._init_local(description, context)
        return {"success": False, "error": f"Unknown init mode: {mode}"}

    def _init_new(self, description: str, ctx: Dict[str, Any]) -> Dict[str, Any]:
        name = ctx.get("name", description[:50])
        target_path = ctx.get("target_path", "")
        if not target_path:
            base = ctx.get("base_path", "D:\\Products")
            safe_name = name.replace(" ", "_").replace("/", "_").replace("\\", "_")
            target_path = os.path.join(base, safe_name)

        tech_stack = {
            "frontend": ctx.get("frontend", ""),
            "backend": ctx.get("backend", ""),
            "database": ctx.get("database", ""),
        }
        dev_mode = ctx.get("dev_mode", "local")

        os.makedirs(target_path, exist_ok=True)
        self._generate_scaffold(target_path, name, tech_stack)
        self._init_git(target_path)

        project = ProjectRecord(
            name=name,
            status=ProjectStatus.ACTIVE.value,
            init_mode=ProjectInitMode.NEW.value,
            target_path=target_path,
            repo_url=ctx.get("repo_url", ""),
            tech_stack=tech_stack,
            metadata={"dev_mode": dev_mode},
        )

        if self._registry:
            result = self._registry.register(project)
            if not result.get("success"):
                return result
            project = self._get_registered(project.project_id)

        return {
            "success": True,
            "action": "project_init",
            "artifacts": {
                "mode": "new",
                "project": project.to_dict() if project else {},
                "target_path": target_path,
                "tech_stack": tech_stack,
                "dev_mode": dev_mode,
                "message": f"Project created at {target_path}",
            },
        }

    def _generate_scaffold(
        self, target_path: str, name: str, tech_stack: Dict[str, str]
    ):
        for d in _DEFAULT_SCAFFOLD_DIRS:
            os.makedirs(os.path.join(target_path, d), exist_ok=True)

        for fname, template in _DEFAULT_SCAFFOLD_FILES.items():
            fpath = os.path.join(target_path, fname)
            if not os.path.exists(fpath):
                with open(fpath, "w", encoding="utf-8") as f:
                    f.write(template.format(name=name))

        backend = tech_stack.get("backend", "")
        if backend in ("flask", "fastapi", "python"):
            req_path = os.path.join(target_path, "requirements.txt")
            if not os.path.exists(req_path):
                with open(req_path, "w", encoding="utf-8") as f:
                    f.write(f"# {backend} dependencies\n")

        frontend = tech_stack.get("frontend", "")
        if frontend in ("react", "vue"):
            src_dir = os.path.join(target_path, "src")
            os.makedirs(src_dir, exist_ok=True)
            index_path = os.path.join(src_dir, "index.js")
            if not os.path.exists(index_path):
                with open(index_path, "w", encoding="utf-8") as f:
                    f.write(f"// {frontend} entry point\n")

    def _init_git(self, target_path: str):
        git_dir = os.path.join(target_path, ".git")
        if not os.path.exists(git_dir):
            try:
                subprocess.run(
                    ["git", "init"],
                    cwd=target_path,
                    capture_output=True,
                    timeout=30,
                )
            except Exception as e:
                logger.warning(f"git init failed for {target_path}: {e}")

    def _init_clone(self, description: str, ctx: Dict[str, Any]) -> Dict[str, Any]:
        repo_url = ctx.get("repo_url", "")
        if not repo_url:
            return {"success": False, "error": "repo_url required for clone mode"}

        name = ctx.get("name", repo_url.rstrip("/").split("/")[-1].replace(".git", ""))
        base = ctx.get("base_path", "D:\\Products")
        target_path = os.path.join(base, name)

        tech_stack = ctx.get("tech_stack", {})
        clone_success = False

        if not os.path.exists(target_path):
            try:
                subprocess.run(
                    ["git", "clone", repo_url, target_path],
                    capture_output=True,
                    timeout=120,
                    check=True,
                )
                clone_success = True
            except subprocess.CalledProcessError as e:
                return {
                    "success": False,
                    "error": f"git clone failed: {e.stderr.decode() if e.stderr else str(e)}",
                }
            except FileNotFoundError:
                return {
                    "success": False,
                    "error": "git not found on PATH",
                }
            except Exception as e:
                return {"success": False, "error": f"git clone error: {e}"}
        else:
            clone_success = True

        if not tech_stack and os.path.exists(target_path):
            tech_stack = self._detect_tech_stack(target_path)

        dev_branch = ctx.get("dev_branch", "dev")
        if clone_success and os.path.exists(target_path):
            try:
                subprocess.run(
                    ["git", "checkout", "-b", dev_branch],
                    cwd=target_path,
                    capture_output=True,
                    timeout=30,
                )
            except Exception:
                pass

        project = ProjectRecord(
            name=name,
            status=ProjectStatus.ACTIVE.value,
            init_mode=ProjectInitMode.CLONE.value,
            target_path=target_path,
            repo_url=repo_url,
            default_branch=ctx.get("default_branch", "main"),
            tech_stack=tech_stack,
            metadata={"dev_mode": "github", "dev_branch": dev_branch},
        )

        if self._registry:
            result = self._registry.register(project)
            if not result.get("success"):
                return result
            project = self._get_registered(project.project_id)

        return {
            "success": True,
            "action": "project_init",
            "artifacts": {
                "mode": "clone",
                "project": project.to_dict() if project else {},
                "target_path": target_path,
                "repo_url": repo_url,
                "tech_stack": tech_stack,
                "message": f"Clone project registered: {name}",
            },
        }

    def _init_local(self, description: str, ctx: Dict[str, Any]) -> Dict[str, Any]:
        target_path = ctx.get("target_path", "")
        if not target_path:
            return {"success": False, "error": "target_path required for local mode"}
        if not os.path.exists(target_path):
            return {"success": False, "error": f"Path does not exist: {target_path}"}

        name = ctx.get("name", os.path.basename(target_path))
        tech_stack = ctx.get("tech_stack", {})

        if not tech_stack:
            tech_stack = self._detect_tech_stack(target_path)

        project = ProjectRecord(
            name=name,
            status=ProjectStatus.ACTIVE.value,
            init_mode=ProjectInitMode.LOCAL.value,
            target_path=target_path,
            tech_stack=tech_stack,
            metadata={"dev_mode": "local"},
        )

        if self._registry:
            result = self._registry.register(project)
            if not result.get("success"):
                return result
            project = self._get_registered(project.project_id)

        return {
            "success": True,
            "action": "project_init",
            "artifacts": {
                "mode": "local",
                "project": project.to_dict() if project else {},
                "target_path": target_path,
                "tech_stack": tech_stack,
                "message": f"Local project registered: {name} at {target_path}",
            },
        }

    def _detect_tech_stack(self, path: str) -> Dict[str, str]:
        stack = {}
        files = set()
        try:
            for root, dirs, filenames in os.walk(path):
                for f in filenames:
                    files.add(f)
                dirs[:] = [
                    d
                    for d in dirs
                    if d not in (".git", "node_modules", "__pycache__", ".venv")
                ]
                if len(files) > 200:
                    break
        except Exception:
            return stack

        if "package.json" in files:
            stack["frontend"] = "react"
        if "requirements.txt" in files:
            stack["backend"] = "python"
        if any(f.endswith(".db") for f in files):
            stack["database"] = "sqlite"
        if not stack.get("backend") and any(f.endswith(".py") for f in files):
            stack["backend"] = "python"

        return stack

    def _get_registered(self, project_id: str) -> ProjectRecord:
        if self._registry:
            result = self._registry.get(project_id)
            if result.get("success"):
                return ProjectRecord.from_dict(result["artifacts"])
        return None
